arch: resnet50
batch-size: 128
dataset: sem
dataset-root: /usr/sci/scratch_nvme/jakobj/nfs/paired-xrd-sem-2
device: cuda
epochs: 10
lr: 0.001
momentum: 0.9
weight-decay: 1.0e-05
workers: 4

seed: -1

# configs for transformations
crop-size: 224
resize-size: 256
transforms: ["randomcrop", "randomhorizontalflip", "randomverticalflip", "randomrotation"]