arch: resnet50
batch-size: 16
dataset: sem
dataset-root: /scratch_nvme/jakobj/nfs/paired-xrd-sem
device: cuda
epochs: 10
lr: 0.001
momentum: 0.9
weight-decay: 1.0e-05
workers: 4

seed: -1

# configs for transformations
crop-size: 224
resize-size: 256
transforms: ["randomcrop", "randomhorizontalflip", "randomverticalflip", "randomrotation"]